# Generated by Django 6.0.6 on 2026-06-21 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrolesrules',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
        migrations.AddField(
            model_name='accessrolesrules',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.businesselement'),
        ),
    ]
